spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:/db/migration/data.sql
      schema-locations: classpath:/db/migration/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none