create table authors (
    id bigserial,
    full_name varchar(255),
    primary key (id)
);

create table genres (
    id bigserial,
    name varchar(255),
    primary key (id)
);

create table books (
    id bigserial,
    title varchar(255),
    author_id bigint references authors (id) on delete cascade,
    genre_id bigint references genres(id) on delete cascade,
    primary key (id)
);

create table comments (
    id bigint generated by default as identity,
    text varchar(255) not null,
    book_id bigint not null,
    primary key (id)
);

alter table if exists comments add constraint FK1ey8gegnanvybix5a025vepf4 foreign key (book_id) references books;